;this file for FamiTone2 library generated by text2data tool

MySongDump_music_data:
	.db 2
	.dw .instruments
	.dw .samples-3
	.dw .song0ch0,.song0ch1,.song0ch2,.song0ch3,.song0ch4,307,256
	.dw .song1ch0,.song1ch1,.song1ch2,.song1ch3,.song1ch4,307,256

.instruments:
	.db $b0 ;instrument $00
	.dw .env1,.env0,.env0
	.db $00
	.db $b0 ;instrument $01
	.dw .env2,.env0,.env0
	.db $00
	.db $b0 ;instrument $02
	.dw .env3,.env0,.env0
	.db $00
	.db $b0 ;instrument $03
	.dw .env4,.env0,.env0
	.db $00

.samples:
.env0:
	.db $c0,$00,$00
.env1:
	.db $c6,$cf,$cc,$c9,$c7,$c6,$c5,$c4,$c2,$00,$08
.env2:
	.db $c3,$c7,$c5,$c4,$c3,$c2,$c1,$c1,$c0,$00,$08
.env3:
	.db $c4,$c3,$c2,$c1,$c0,$00,$04
.env4:
	.db $c2,$06,$c1,$00,$02


.song0ch0:
	.db $fb,$07
.song0ch0loop:
.ref0:
	.db $80,$3a,$85,$84,$30,$80,$32,$83,$2c,$91,$2d,$33,$37,$38,$87,$36
	.db $83
.ref1:
	.db $3a,$85,$84,$30,$80,$32,$83,$2c,$91,$33,$33,$33,$30,$30,$83,$30
	.db $85
.ref2:
	.db $3a,$85,$84,$30,$80,$32,$83,$2c,$91,$2d,$33,$37,$38,$87,$36,$83
.ref3:
	.db $81,$32,$33,$33,$33,$30,$85,$31,$29,$36,$37,$37,$37,$32,$83,$31
	.db $29,$30,$81
.ref4:
	.db $33,$00,$85,$31,$33,$00,$85,$31,$33,$00,$85,$31,$32,$85,$36,$85
.ref5:
	.db $33,$00,$85,$31,$33,$00,$85,$31,$33,$00,$85,$31,$33,$29,$29,$82
	.db $28,$81
	.db $ff,$0e
	.dw .ref0
	.db $ff,$0f
	.dw .ref1
	.db $ff,$0e
	.dw .ref2
	.db $ff,$13
	.dw .ref3
	.db $ff,$10
	.dw .ref4
	.db $ff,$11
	.dw .ref5
	.db $fd
	.dw .song0ch0loop

.song0ch1:
.song0ch1loop:
.ref12:
	.db $00,$85,$82,$14,$85,$00,$85,$15,$00,$89,$14,$85,$1b,$01,$1f,$00
	.db $81
.ref13:
	.db $00,$85,$14,$85,$00,$85,$15,$00,$89,$14,$85,$1b,$01,$1f,$00,$81
	.db $ff,$10
	.dw .ref13
	.db $ff,$10
	.dw .ref13
	.db $ff,$10
	.dw .ref13
	.db $ff,$10
	.dw .ref13
.ref18:
	.db $81,$84,$52,$87,$4a,$83,$52,$87,$4a,$83,$52,$87,$4a,$83,$4e,$87
	.db $4e,$81
.ref19:
	.db $81,$52,$87,$4a,$83,$52,$87,$4a,$83,$52,$87,$4a,$85,$49,$48,$85
.ref20:
	.db $81,$52,$87,$4a,$83,$52,$87,$4a,$83,$52,$87,$4a,$83,$4e,$87,$4e
	.db $81
.ref21:
	.db $81,$52,$53,$53,$53,$4e,$85,$4f,$49,$4e,$4f,$4f,$4f,$48,$83,$49
	.db $40,$85
	.db $ff,$10
	.dw .ref12
	.db $ff,$10
	.dw .ref13
	.db $fd
	.dw .song0ch1loop

.song0ch2:
.song0ch2loop:
.ref24:
	.db $80,$4b,$3b,$01,$3b,$4b,$3b,$01,$3b,$4b,$3b,$01,$3b,$4b,$3b,$01
	.db $3a,$81
.ref25:
	.db $4b,$3b,$01,$3b,$4b,$3b,$01,$3b,$4b,$3b,$01,$3b,$4b,$3b,$01,$3a
	.db $81
	.db $ff,$11
	.dw .ref25
	.db $ff,$11
	.dw .ref25
	.db $ff,$11
	.dw .ref25
	.db $ff,$11
	.dw .ref25
	.db $ff,$11
	.dw .ref25
	.db $ff,$11
	.dw .ref25
	.db $ff,$11
	.dw .ref25
	.db $ff,$11
	.dw .ref25
	.db $ff,$11
	.dw .ref25
	.db $ff,$11
	.dw .ref25
	.db $fd
	.dw .song0ch2loop

.song0ch3:
.song0ch3loop:
.ref36:
	.db $84,$13,$13,$00,$82,$16,$86,$1b,$84,$13,$13,$00,$82,$16,$86,$1b
	.db $84,$13,$13,$00,$82,$16,$86,$1b,$84,$13,$13,$00,$82,$16,$86,$1a
	.db $81
	.db $ff,$15
	.dw .ref36
	.db $ff,$15
	.dw .ref36
	.db $ff,$15
	.dw .ref36
	.db $ff,$15
	.dw .ref36
	.db $ff,$15
	.dw .ref36
	.db $ff,$15
	.dw .ref36
	.db $ff,$15
	.dw .ref36
	.db $ff,$15
	.dw .ref36
	.db $ff,$15
	.dw .ref36
	.db $ff,$15
	.dw .ref36
	.db $ff,$15
	.dw .ref36
	.db $fd
	.dw .song0ch3loop

.song0ch4:
.song0ch4loop:
.ref48:
	.db $bf
.ref49:
	.db $bf
.ref50:
	.db $bf
.ref51:
	.db $bf
.ref52:
	.db $bf
.ref53:
	.db $bf
.ref54:
	.db $bf
.ref55:
	.db $bf
.ref56:
	.db $bf
.ref57:
	.db $bf
.ref58:
	.db $bf
.ref59:
	.db $bf
	.db $fd
	.dw .song0ch4loop


.song1ch0:
	.db $fb,$06
.song1ch0loop:
.ref60:
	.db $bf
	.db $fd
	.dw .song1ch0loop

.song1ch1:
.song1ch1loop:
.ref61:
	.db $bf
	.db $fd
	.dw .song1ch1loop

.song1ch2:
.song1ch2loop:
.ref62:
	.db $82,$33,$00,$89,$33,$00,$89,$33,$00,$89,$2d,$01,$2c,$85
	.db $fd
	.dw .song1ch2loop

.song1ch3:
.song1ch3loop:
.ref63:
	.db $84,$16,$00,$83,$16,$00,$83,$16,$00,$83,$12,$00,$83,$16,$00,$83
	.db $16,$00,$83,$16,$00,$83,$12,$00,$83
	.db $fd
	.dw .song1ch3loop

.song1ch4:
.song1ch4loop:
.ref64:
	.db $bf
	.db $fd
	.dw .song1ch4loop
